- name: "This playbook is to apply patches to ubuntu servers"
  hosts: webservers
  become: true
  tasks:
  - name: install nginx
    apt: 
      name:nginx 
      state:latest
  - name: copy index.html template
    template:
      src: 
        index.html
      dest: 
        /usr/share/nginx/html
    notify: 
      restart nginx
  - name: enable and start service
    service:
    name: 
      nginx
    enabled: yes
    state: started
